version: "3"

tasks:
  run:
    desc: Run GUI
    aliases:
      - r
    cmds:
      - uv run ./gamepadla_plus {{.CLI_ARGS}}

  check:
    desc: Lint and format project.
    aliases:
      - c
    cmds:
      - uv run ruff check
      - uv run ty check

  try-fix:
    desc: Lint and format project.
    cmds:
      - uv run ruff check --fix
      - uv run ty check --fix

  compile-windows-current-arch:
    desc: Compile a standalone windows executable with nuitka.
    cmd: >
      uv run --only-group package nuitka
      --mode=standalone
      --windows-icon-from-ico=icon/gamepadla-plus.ico
      --enable-plugins=tk-inter
      --noinclude-default-mode=error
      --noinclude-unittest-mode=allow
      --nowarn-mnemonic=unwanted-module
      --assume-yes-for-downloads
      --windows-console-mode=hide
      --output-filename="Gamepadla+"
      --output-folder-name=Gamepadla+
      --output-dir=dist
      gamepadla_plus

  fetch-third-party-licenses:
    cmd: >
      uv run --only-group license-fetching pip-licenses
      --with-system
      --from=all
      --format=plain-vertical
      --with-urls
      --with-authors
      --with-license-file
      --output-file THIRD-PARTY-LICENSES.txt

  attach-python-license-to-third-party-licenses:
    cmd: pwsh helper/Add-PythonInfoToThirdPartyLicenses.ps1

  copy-docs-and-licenses-into-distribution:
    cmd: pwsh helper/Copy-DocsIntoDist.ps1
