name: Package Release

on:
  release:
    types:
      - published

jobs:
  build-release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        run: uv python install 3.12

      - name: Fetch Licenses
        run: uv run pip-licenses --with-system --from=all --format=plain-vertical --with-urls --with-authors --output-file THIRD-PARTY-LICENSES.txt

      
