name: PyPI Release

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  pypi-release:
    name: Release Python Package
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
    - uses: actions/checkout@v5

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Set up Python
      run: uv python install

    - name: Clean dist directory
      run: rm -rf dist

    - name: Build Wheel
      run: uv build

    - name: Show built artifacts
      run: ls -la dist

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
